name = "Cobblemon"
author = "Douglas Parker"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deaab2d45b4972c8ac2dd71fff9b13de2bc1da698a026a9ea0ba8336b4e16e8d"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
