name = "Cobblemon"
author = "Douglas Parker"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ede9d99f09c7ff811825d7813eeb538dddfd8508789a84d24c8605565ea85f4"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
