name = "Cobblemon"
author = "Douglas Parker"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "841d072b716d51014c805287f3a26efe5222260893210851f17a809ec82b98ac"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
