name = "Cobblemon"
author = "Douglas Parker"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca73a2c705311b07fafaccbd56d575154f056a405f0acc289c59c7955f70571a"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
