name = "Cobblemon"
author = "Douglas Parker"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "639911f3926fa4cf92263cdeed9e9798478a39046392d4e753f7206f23b00458"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
