name = "Cobblemon"
author = "Douglas Parker"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fb64ee2c5e9b191a5b0759f5946105d925b18556087a1042f7e25d55a066c27"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
