name = "Cobblemon"
author = "Douglas Parker"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eec03afb92e468f91eafe58ef3ec1609132c3fd28a7e363fbbec80bfe67ddb9d"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
