name = "Cobblemon"
author = "Douglas Parker"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8e38b92df70769a9059314e402e062f99ae39fee79df12dc39e31622942731d"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
