name = "Cobblemon"
author = "Douglas Parker"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a94b811a1b3e0578dbd87ed7d2cc0a2b8d410310232b49c2276bd74ad3e3f42"

[versions]
fabric = "0.14.20"
minecraft = "1.19.2"
